f = open('C:\\Cloud\\BaiduSyncdisk\\Code\\Python\\LearnPythonFromMooc\\Python进阶课程\\第6章 Python读写文件\\test.txt','r')
print(type(f))
s = f.read(5)
print(s)
s = f.read(5)
print(s)
s = f.readline(5)
print(s)
s = f.readlines()
print(s)
f.close()
f = open("Python进阶课程\\第6章 Python读写文件\\6-2 Python打开文本文件.py")
content = f.readlines()
print(content)
f.close()